from pathlib import Path

from pydantic import Field
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):

    ENVIRONMENT: str = "development"
    API_PORT: int = 8000

    DB_HOST: str
    DB_PORT: int = 5432
    DB_USER: str
    DB_PASSWORD: str
    DB_NAME: str

    REDIS_HOST: str = "localhost"
    REDIS_PORT: int = 6379
    REDIS_PASSWORD: str | None = None

    RABBITMQ_HOST: str = "localhost"
    RABBITMQ_PORT: int = 5672
    RABBITMQ_USER: str = "guest"
    RABBITMQ_PASSWORD: str = "guest"

    SECRET_KEY: str
    ALGORITHM: str = "HS256"
    ACCESS_TOKEN_EXPIRE_MINUTES: int = 30
    REFRESH_TOKEN_EXPIRE_MINUTES: int = 60 * 24 * 7

    GOOGLE_CLIENT_ID: str
    GOOGLE_CLIENT_SECRET: str
    GOOGLE_REDIRECT_URI: str = "http://localhost:5685/api/v1/unirio/auth/google/callback"
    FRONTEND_AUTH_SUCCESS_URL: str = "http://localhost:4200/"
    FRONTEND_AUTH_ERROR_URL: str = "http://localhost:4200/signin"
    ALLOWED_GOOGLE_DOMAINS: str = "edu.unirio.br"
    GOOGLE_OAUTH_STATE_TTL_SECONDS: int = 300

    HTTP_CLIENT_TIMEOUT_SECONDS: float = 10.0
    HTTP_CLIENT_MAX_CONNECTIONS: int = 100
    HTTP_CLIENT_MAX_KEEPALIVE_CONNECTIONS: int = 20

    SIE_API_BASE_URL: str = "https://api.unirio.br/api/v2"
    SIE_EMAIL: str | None = None
    SIE_PASSWORD: str | None = None
    SIE_SYNC_PAGE_SIZE: int = 500
    SIE_SYNC_INTERVAL_DAYS: int = 15

    COOKIE_AUTH: str = "auth"
    COOKIE_AUTH_REFRESH: str = "refresh"
    COOKIE_AUTH_RESET: str = "reset"

    ROLE_RANK_BY_NAME: dict[str, int] = Field(
        default_factory=lambda: {
            "TECNICO": 2,
            "PROFESSOR": 2,
            "ADMIN": 3,
        }
    )

    ALLOWED_EMAIL_DOMAIN: str = "edu.unirio.br"

    EMAIL_FROM: str = "no-reply@edu.unirio.br"
    EMAIL_QUEUE: str = "email_dispatch"

    RESET_CODE_REDIS_TTL_SECONDS: int = 300
    RESET_COOKIE_MAX_AGE: int = 900

    RATE_LIMIT_KEY_PREFIX: str = "rate_limit"
    RATE_LIMIT_LOGIN_MAX_REQUESTS: int = 5
    RATE_LIMIT_LOGIN_WINDOW_SECONDS: int = 60
    RATE_LIMIT_FORGET_PASSWORD_MAX_REQUESTS: int = 3
    RATE_LIMIT_FORGET_PASSWORD_WINDOW_SECONDS: int = 300
    RATE_LIMIT_VALIDATE_CODE_MAX_REQUESTS: int = 5
    RATE_LIMIT_VALIDATE_CODE_WINDOW_SECONDS: int = 300

    PROJECTS_SORT_TITULO_ASC: str = "titulo_asc"
    PROJECTS_SORT_TITULO_DESC: str = "titulo_desc"
    PROJECTS_SORT_DATA_DESC: str = "data_desc"
    PROJECTS_DEFAULT_SORT: str = PROJECTS_SORT_DATA_DESC
    PROJECTS_ALLOWED_SORT_OPTIONS: tuple[str, str, str] = (
        PROJECTS_SORT_TITULO_ASC,
        PROJECTS_SORT_TITULO_DESC,
        PROJECTS_SORT_DATA_DESC,
    )
    PROJECTS_DEFAULT_PAGE: int = 1
    PROJECTS_DEFAULT_PAGE_SIZE: int = 20
    PROJECTS_MAX_PAGE_SIZE: int = 100
    PROJECTS_DEFAULT_ONLY_ENABLED: bool = True
    PROJECT_COVER_UPLOAD_DIR: str = Field(
        default_factory=lambda: str(
            Path(__file__).resolve().parents[3]
            / "siepa-front"
            / "src"
            / "assets"
            / "project-covers"
        )
    )
    PROJECT_COVER_PUBLIC_PATH: str = "assets/project-covers"
    PROJECT_COVER_MAX_BYTES: int = 5 * 1024 * 1024

    model_config = SettingsConfigDict(env_file=".env", env_file_encoding="utf-8-sig", extra="ignore")


settings = Settings()

# Backward-compatible aliases for modules still importing constants directly.
COOKIE_AUTH = settings.COOKIE_AUTH
COOKIE_AUTH_REFRESH = settings.COOKIE_AUTH_REFRESH
COOKIE_AUTH_RESET = settings.COOKIE_AUTH_RESET
ROLE_RANK_BY_NAME = settings.ROLE_RANK_BY_NAME

ALLOWED_EMAIL_DOMAIN = settings.ALLOWED_EMAIL_DOMAIN
EMAIL_FROM = settings.EMAIL_FROM
EMAIL_QUEUE = settings.EMAIL_QUEUE

RESET_CODE_REDIS_TTL_SECONDS = settings.RESET_CODE_REDIS_TTL_SECONDS
RESET_COOKIE_MAX_AGE = settings.RESET_COOKIE_MAX_AGE

RATE_LIMIT_KEY_PREFIX = settings.RATE_LIMIT_KEY_PREFIX
RATE_LIMIT_LOGIN_MAX_REQUESTS = settings.RATE_LIMIT_LOGIN_MAX_REQUESTS
RATE_LIMIT_LOGIN_WINDOW_SECONDS = settings.RATE_LIMIT_LOGIN_WINDOW_SECONDS
RATE_LIMIT_FORGET_PASSWORD_MAX_REQUESTS = settings.RATE_LIMIT_FORGET_PASSWORD_MAX_REQUESTS
RATE_LIMIT_FORGET_PASSWORD_WINDOW_SECONDS = settings.RATE_LIMIT_FORGET_PASSWORD_WINDOW_SECONDS
RATE_LIMIT_VALIDATE_CODE_MAX_REQUESTS = settings.RATE_LIMIT_VALIDATE_CODE_MAX_REQUESTS
RATE_LIMIT_VALIDATE_CODE_WINDOW_SECONDS = settings.RATE_LIMIT_VALIDATE_CODE_WINDOW_SECONDS

PROJECTS_DEFAULT_SORT = settings.PROJECTS_DEFAULT_SORT
PROJECTS_ALLOWED_SORT_OPTIONS = settings.PROJECTS_ALLOWED_SORT_OPTIONS
PROJECTS_DEFAULT_PAGE = settings.PROJECTS_DEFAULT_PAGE
PROJECTS_DEFAULT_PAGE_SIZE = settings.PROJECTS_DEFAULT_PAGE_SIZE
PROJECTS_MAX_PAGE_SIZE = settings.PROJECTS_MAX_PAGE_SIZE
PROJECTS_DEFAULT_ONLY_ENABLED = settings.PROJECTS_DEFAULT_ONLY_ENABLED
PROJECTS_SORT_TITULO_ASC = settings.PROJECTS_SORT_TITULO_ASC
PROJECTS_SORT_TITULO_DESC = settings.PROJECTS_SORT_TITULO_DESC
PROJECTS_SORT_DATA_DESC = settings.PROJECTS_SORT_DATA_DESC
PROJECT_COVER_UPLOAD_DIR = settings.PROJECT_COVER_UPLOAD_DIR
PROJECT_COVER_PUBLIC_PATH = settings.PROJECT_COVER_PUBLIC_PATH
PROJECT_COVER_MAX_BYTES = settings.PROJECT_COVER_MAX_BYTES

HTTP_CLIENT_TIMEOUT_SECONDS = settings.HTTP_CLIENT_TIMEOUT_SECONDS
HTTP_CLIENT_MAX_CONNECTIONS = settings.HTTP_CLIENT_MAX_CONNECTIONS
HTTP_CLIENT_MAX_KEEPALIVE_CONNECTIONS = settings.HTTP_CLIENT_MAX_KEEPALIVE_CONNECTIONS
